name: Example Config
version: 1.0.0
schema: v1

models:
  - name: DeepSeek Coder (Local)
    provider: ollama
    model: deepseek-coder:6.7b
    context_length: 8192
  - name: my gpt-5
    provider: openai
    model: gpt-5
    apiKey: YOUR_OPENAI_API_KEY_HERE
  - uses: ollama/qwen2.5-coder-7b
  - uses: anthropic/claude-4-sonnet
    with:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

defaultModel: DeepSeek Coder (Local)

mcpServers:
  - uses: anthropic/memory-mcp
